// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity_events.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listActivityForAssignment = `-- name: ListActivityForAssignment :many
SELECT
    e.id, e.event_type, e.patient_id, e.assignment_id, e.actor_id, e.is_developer_data, e.metadata, e.created_at,
    u.full_name AS actor_name
FROM activity_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.assignment_id = $1
  AND e.is_developer_data = is_developer_user($2)
ORDER BY e.created_at DESC
`

type ListActivityForAssignmentParams struct {
	AssignmentID *uuid.UUID `json:"assignment_id"`
	ViewerID     uuid.UUID  `json:"viewer_id"`
}

type ListActivityForAssignmentRow struct {
	ID              uuid.UUID          `json:"id"`
	EventType       string             `json:"event_type"`
	PatientID       *uuid.UUID         `json:"patient_id"`
	AssignmentID    *uuid.UUID         `json:"assignment_id"`
	ActorID         *uuid.UUID         `json:"actor_id"`
	IsDeveloperData bool               `json:"is_developer_data"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActorName       *string            `json:"actor_name"`
}

// One assignment's full history (created, started, ready for review,
// reviewed, links sent, reminders sent), most recent first.
func (q *Queries) ListActivityForAssignment(ctx context.Context, arg ListActivityForAssignmentParams) ([]*ListActivityForAssignmentRow, error) {
	rows, err := q.db.Query(ctx, listActivityForAssignment, arg.AssignmentID, arg.ViewerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActivityForAssignmentRow
	for rows.Next() {
		var i ListActivityForAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PatientID,
			&i.AssignmentID,
			&i.ActorID,
			&i.IsDeveloperData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityForPatient = `-- name: ListActivityForPatient :many
SELECT
    e.id, e.event_type, e.patient_id, e.assignment_id, e.actor_id, e.is_developer_data, e.metadata, e.created_at,
    u.full_name AS actor_name
FROM activity_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.patient_id = $1
  AND e.is_developer_data = is_developer_user($2)
ORDER BY e.created_at DESC
LIMIT $4 OFFSET $3
`

type ListActivityForPatientParams struct {
	PatientID *uuid.UUID `json:"patient_id"`
	ViewerID  uuid.UUID  `json:"viewer_id"`
	RowOffset int32      `json:"row_offset"`
	RowLimit  int32      `json:"row_limit"`
}

type ListActivityForPatientRow struct {
	ID              uuid.UUID          `json:"id"`
	EventType       string             `json:"event_type"`
	PatientID       *uuid.UUID         `json:"patient_id"`
	AssignmentID    *uuid.UUID         `json:"assignment_id"`
	ActorID         *uuid.UUID         `json:"actor_id"`
	IsDeveloperData bool               `json:"is_developer_data"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ActorName       *string            `json:"actor_name"`
}

// One patient's timeline (patient detail view), most recent first.
func (q *Queries) ListActivityForPatient(ctx context.Context, arg ListActivityForPatientParams) ([]*ListActivityForPatientRow, error) {
	rows, err := q.db.Query(ctx, listActivityForPatient,
		arg.PatientID,
		arg.ViewerID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListActivityForPatientRow
	for rows.Next() {
		var i ListActivityForPatientRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PatientID,
			&i.AssignmentID,
			&i.ActorID,
			&i.IsDeveloperData,
			&i.Metadata,
			&i.CreatedAt,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentActivity = `-- name: ListRecentActivity :many
SELECT
    e.id, e.event_type, e.patient_id, e.assignment_id, e.actor_id, e.is_developer_data, e.metadata, e.created_at,
    p.full_name AS patient_name,
    u.full_name AS actor_name
FROM activity_events e
LEFT JOIN patients p ON p.id = e.patient_id
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.is_developer_data = is_developer_user($1)
ORDER BY e.created_at DESC
LIMIT $3 OFFSET $2
`

type ListRecentActivityParams struct {
	ViewerID  uuid.UUID `json:"viewer_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

type ListRecentActivityRow struct {
	ID              uuid.UUID          `json:"id"`
	EventType       string             `json:"event_type"`
	PatientID       *uuid.UUID         `json:"patient_id"`
	AssignmentID    *uuid.UUID         `json:"assignment_id"`
	ActorID         *uuid.UUID         `json:"actor_id"`
	IsDeveloperData bool               `json:"is_developer_data"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	PatientName     *string            `json:"patient_name"`
	ActorName       *string            `json:"actor_name"`
}

// Dashboard-wide "Recent activity" feed, most recent first.
func (q *Queries) ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]*ListRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, listRecentActivity, arg.ViewerID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRecentActivityRow
	for rows.Next() {
		var i ListRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.PatientID,
			&i.AssignmentID,
			&i.ActorID,
			&i.IsDeveloperData,
			&i.Metadata,
			&i.CreatedAt,
			&i.PatientName,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logActivityEvent = `-- name: LogActivityEvent :exec

SELECT log_activity_event(
    $1, $2, $3, $4
)
`

type LogActivityEventParams struct {
	EventType    string    `json:"event_type"`
	PatientID    uuid.UUID `json:"patient_id"`
	AssignmentID uuid.UUID `json:"assignment_id"`
	Metadata     []byte    `json:"metadata"`
}

// activity_events.sql
//
// sqlc queries for the activity_events table.
//
// Unlike every other file in this set, this table is populated almost
// entirely by triggers (trigger_log_patient_created,
// trigger_log_patient_active_changed, trigger_log_assignment_events,
// trigger_log_link_sent, trigger_log_reminder_sent — see the migration),
// all funneling through the shared log_activity_event() function. There
// isn't a "CreateActivityEvent" query here for the app to call directly
// with raw columns; LogActivityEvent below just calls that same shared
// function, so any manual/ad-hoc event the app wants to record gets
// exactly the same is_developer_data + actor_id handling as every
// trigger-generated one, rather than a second, possibly-diverging
// implementation of that logic.
//
// Visibility: is_developer_data lives directly ON this table (stamped
// once at write time — see the column comment in the migration for
// why), not derived via a join at read time. So the partition check
// here is just a plain column comparison, no join required for
// correctness:
//
//	is_developer_data = is_developer_user(viewer_id)
//
// The LEFT JOINs to patients/assignments/users in the list queries
// below are purely for display (patient name, test name, actor name) —
// all nullable, since a referenced patient/assignment/user may have
// since been deleted while the event itself persists as history.
// For any event the app wants to record that isn't already covered by
// a trigger. Delegates entirely to log_activity_event(), so
// is_developer_data and actor_id are computed identically to every
// trigger-driven row.
func (q *Queries) LogActivityEvent(ctx context.Context, arg LogActivityEventParams) error {
	_, err := q.db.Exec(ctx, logActivityEvent,
		arg.EventType,
		arg.PatientID,
		arg.AssignmentID,
		arg.Metadata,
	)
	return err
}
