// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_verifications.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredEmailVerifications = `-- name: CleanupExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < NOW() OR used = TRUE
`

func (q *Queries) CleanupExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredEmailVerifications)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    id, user_id, token, email, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, token, email, expires_at, created_at
`

type CreateEmailVerificationParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateEmailVerificationRow struct {
	ID        uuid.UUID          `json:"id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (*CreateEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Email,
		arg.ExpiresAt,
	)
	var i CreateEmailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteEmailVerificationByUserID = `-- name: DeleteEmailVerificationByUserID :exec
DELETE FROM email_verifications
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationByUserID, userID)
	return err
}

const getEmailVerificationByID = `-- name: GetEmailVerificationByID :one
SELECT id, user_id, token, email, expires_at, used, created_at
FROM email_verifications
WHERE id = $1
`

type GetEmailVerificationByIDRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEmailVerificationByID(ctx context.Context, id uuid.UUID) (*GetEmailVerificationByIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByID, id)
	var i GetEmailVerificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return &i, err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, user_id, token, email, expires_at, used, created_at
FROM email_verifications
WHERE token = $1
  AND used = FALSE
  AND expires_at > NOW()
`

type GetEmailVerificationByTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (*GetEmailVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByToken, token)
	var i GetEmailVerificationByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return &i, err
}

const getEmailVerificationByUserID = `-- name: GetEmailVerificationByUserID :one
SELECT id, user_id, token, email, expires_at, used, created_at
FROM email_verifications
WHERE user_id = $1
`

type GetEmailVerificationByUserIDRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	Email     string             `json:"email"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) (*GetEmailVerificationByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByUserID, userID)
	var i GetEmailVerificationByUserIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Email,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return &i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET used = TRUE
WHERE token = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, token)
	return err
}
