// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssignmentMode string

const (
	AssignmentModeINCLINIC AssignmentMode = "IN_CLINIC"
	AssignmentModeREMOTE   AssignmentMode = "REMOTE"
)

func (e *AssignmentMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentMode(s)
	case string:
		*e = AssignmentMode(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentMode: %T", src)
	}
	return nil
}

type NullAssignmentMode struct {
	AssignmentMode AssignmentMode `json:"assignment_mode"`
	Valid          bool           `json:"valid"` // Valid is true if AssignmentMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentMode) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentMode), nil
}

type AssignmentStatus string

const (
	AssignmentStatusASSIGNED       AssignmentStatus = "ASSIGNED"
	AssignmentStatusINPROGRESS     AssignmentStatus = "IN_PROGRESS"
	AssignmentStatusREADYFORREVIEW AssignmentStatus = "READY_FOR_REVIEW"
	AssignmentStatusCOMPLETED      AssignmentStatus = "COMPLETED"
)

func (e *AssignmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssignmentStatus(s)
	case string:
		*e = AssignmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AssignmentStatus: %T", src)
	}
	return nil
}

type NullAssignmentStatus struct {
	AssignmentStatus AssignmentStatus `json:"assignment_status"`
	Valid            bool             `json:"valid"` // Valid is true if AssignmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssignmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AssignmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssignmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssignmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssignmentStatus), nil
}

type ScoringMethod string

const (
	ScoringMethodSUMBANDED         ScoringMethod = "SUM_BANDED"
	ScoringMethodMULTISCALEPROFILE ScoringMethod = "MULTISCALE_PROFILE"
	ScoringMethodSUBSCALEBANDED    ScoringMethod = "SUBSCALE_BANDED"
)

func (e *ScoringMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoringMethod(s)
	case string:
		*e = ScoringMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoringMethod: %T", src)
	}
	return nil
}

type NullScoringMethod struct {
	ScoringMethod ScoringMethod `json:"scoring_method"`
	Valid         bool          `json:"valid"` // Valid is true if ScoringMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoringMethod) Scan(value interface{}) error {
	if value == nil {
		ns.ScoringMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoringMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoringMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoringMethod), nil
}

type Sex string

const (
	SexMALE   Sex = "MALE"
	SexFEMALE Sex = "FEMALE"
)

func (e *Sex) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Sex(s)
	case string:
		*e = Sex(s)
	default:
		return fmt.Errorf("unsupported scan type for Sex: %T", src)
	}
	return nil
}

type NullSex struct {
	Sex   Sex  `json:"sex"`
	Valid bool `json:"valid"` // Valid is true if Sex is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSex) Scan(value interface{}) error {
	if value == nil {
		ns.Sex, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Sex.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSex) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Sex), nil
}

type TestDomain string

const (
	TestDomainDEPRESSION  TestDomain = "DEPRESSION"
	TestDomainANXIETY     TestDomain = "ANXIETY"
	TestDomainSOMATIC     TestDomain = "SOMATIC"
	TestDomainPERSONALITY TestDomain = "PERSONALITY"
	TestDomainSTRESS      TestDomain = "STRESS"
	TestDomainTRAUMA      TestDomain = "TRAUMA"
	TestDomainMULTI       TestDomain = "MULTI"
)

func (e *TestDomain) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TestDomain(s)
	case string:
		*e = TestDomain(s)
	default:
		return fmt.Errorf("unsupported scan type for TestDomain: %T", src)
	}
	return nil
}

type NullTestDomain struct {
	TestDomain TestDomain `json:"test_domain"`
	Valid      bool       `json:"valid"` // Valid is true if TestDomain is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTestDomain) Scan(value interface{}) error {
	if value == nil {
		ns.TestDomain, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TestDomain.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTestDomain) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TestDomain), nil
}

type ActivityEvent struct {
	ID              uuid.UUID          `json:"id"`
	EventType       string             `json:"event_type"`
	PatientID       pgtype.UUID        `json:"patient_id"`
	AssignmentID    pgtype.UUID        `json:"assignment_id"`
	ActorID         pgtype.UUID        `json:"actor_id"`
	IsDeveloperData bool               `json:"is_developer_data"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Assignment struct {
	ID              uuid.UUID          `json:"id"`
	PatientID       uuid.UUID          `json:"patient_id"`
	TestCode        string             `json:"test_code"`
	Mode            AssignmentMode     `json:"mode"`
	Status          AssignmentStatus   `json:"status"`
	AssignedBy      pgtype.UUID        `json:"assigned_by"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	IsDeveloperData bool               `json:"is_developer_data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AssignmentMmpiIndication struct {
	ID                 uuid.UUID `json:"id"`
	AssignmentResultID uuid.UUID `json:"assignment_result_id"`
	CategoryTitle      string    `json:"category_title"`
	IndicationText     string    `json:"indication_text"`
	DisplayOrder       int16     `json:"display_order"`
}

type AssignmentMmpiScale struct {
	ID                 uuid.UUID      `json:"id"`
	AssignmentResultID uuid.UUID      `json:"assignment_result_id"`
	ParentScaleID      pgtype.UUID    `json:"parent_scale_id"`
	CategoryTitle      string         `json:"category_title"`
	ScaleCode          *string        `json:"scale_code"`
	ScaleName          string         `json:"scale_name"`
	ScaleDescription   *string        `json:"scale_description"`
	ScalePurpose       *string        `json:"scale_purpose"`
	RawScore           pgtype.Numeric `json:"raw_score"`
	Score              pgtype.Numeric `json:"score"`
	DisplayOrder       int16          `json:"display_order"`
}

type AssignmentReminder struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	SentBy       pgtype.UUID        `json:"sent_by"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
}

type AssignmentResult struct {
	ID              uuid.UUID          `json:"id"`
	AssignmentID    uuid.UUID          `json:"assignment_id"`
	Responses       []byte             `json:"responses"`
	RawScores       []byte             `json:"raw_scores"`
	DurationSeconds *int32             `json:"duration_seconds"`
	ScoredAt        pgtype.Timestamptz `json:"scored_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AssignmentSumBandResult struct {
	AssignmentResultID    uuid.UUID      `json:"assignment_result_id"`
	HeadlineScore         string         `json:"headline_score"`
	NumericScore          pgtype.Numeric `json:"numeric_score"`
	ScaleLabel            string         `json:"scale_label"`
	SeverityLabel         string         `json:"severity_label"`
	InterpretationSummary string         `json:"interpretation_summary"`
}

type EmailVerification struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordReset struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Patient struct {
	ID              uuid.UUID          `json:"id"`
	Mrn             string             `json:"mrn"`
	FullName        string             `json:"full_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	DateOfBirth     pgtype.Date        `json:"date_of_birth"`
	Sex             *Sex               `json:"sex"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	IsDeveloperData bool               `json:"is_developer_data"`
	IsActive        bool               `json:"is_active"`
	ComputedStatus  *AssignmentStatus  `json:"computed_status"`
	LastActivityAt  pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Notes           string             `json:"notes"`
}

type PendingAuthChallenge struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Mode       string             `json:"mode"`
	Secret     *string            `json:"secret"`
	RememberMe bool               `json:"remember_me"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RemoteAccessToken struct {
	ID           uuid.UUID          `json:"id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	TokenHash    string             `json:"token_hash"`
	SentToEmail  string             `json:"sent_to_email"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	ResendCount  int32              `json:"resend_count"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
	Revoked      bool               `json:"revoked"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	IpAddress        *string            `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	RememberMe       bool               `json:"remember_me"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Revoked          bool               `json:"revoked"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type TestDefinition struct {
	Code                   string             `json:"code"`
	Name                   string             `json:"name"`
	Domain                 TestDomain         `json:"domain"`
	ScoringMethod          ScoringMethod      `json:"scoring_method"`
	RequiresSex            bool               `json:"requires_sex"`
	ItemCount              int16              `json:"item_count"`
	TypicalDurationMinutes int16              `json:"typical_duration_minutes"`
	IsActive               bool               `json:"is_active"`
	SourcePath             string             `json:"source_path"`
	SourceChecksum         string             `json:"source_checksum"`
	Version                int32              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type TwofaBackupCode struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaSecret     *string            `json:"twofa_secret"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}
