// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_resets.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredPasswordResets = `-- name: CleanupExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < NOW() OR used = TRUE
`

func (q *Queries) CleanupExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredPasswordResets)
	return err
}

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (
    id, user_id, token, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, token, expires_at, created_at
`

type CreatePasswordResetParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreatePasswordResetRow struct {
	ID        uuid.UUID          `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (*CreatePasswordResetRow, error) {
	row := q.db.QueryRow(ctx, createPasswordReset,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i CreatePasswordResetRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deletePasswordResetByUserID = `-- name: DeletePasswordResetByUserID :exec
DELETE FROM password_resets
WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetByUserID, userID)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token, expires_at, used, created_at
FROM password_resets
WHERE token = $1
  AND used = FALSE
  AND expires_at > NOW()
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, token string) (*PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return &i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET used = TRUE
WHERE token = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, token)
	return err
}
