// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patients.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countActivePatients = `-- name: CountActivePatients :one
SELECT COUNT(*) FROM patients
WHERE is_active
  AND is_developer_data = is_developer_user($1)
`

// Backs a dashboard "Active patients" stat. For a developer viewer,
// this counts only their team's developer-flagged patients — real
// patients are entirely outside a developer's view, by design.
func (q *Queries) CountActivePatients(ctx context.Context, viewerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActivePatients, viewerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (
    id, mrn, full_name, email, phone, date_of_birth, sex, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes
`

type CreatePatientParams struct {
	ID          uuid.UUID   `json:"id"`
	Mrn         string      `json:"mrn"`
	FullName    string      `json:"full_name"`
	Email       *string     `json:"email"`
	Phone       *string     `json:"phone"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Sex         *Sex        `json:"sex"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

// is_developer_data is NOT a column here — it's stamped automatically
// by trigger_mark_patient_developer_data based on created_by's role, so
// there's no path for the app to get this wrong or forget to set it,
// and no path for a real user to accidentally create a patient that
// lands in the developer partition or vice versa.
func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.ID,
		arg.Mrn,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.Sex,
		arg.CreatedBy,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Mrn,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Sex,
		&i.CreatedBy,
		&i.IsDeveloperData,
		&i.IsActive,
		&i.ComputedStatus,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return &i, err
}

const deletePatient = `-- name: DeletePatient :exec
DELETE FROM patients
WHERE id = $1
  AND is_developer_data = is_developer_user($2)
`

type DeletePatientParams struct {
	ID       uuid.UUID `json:"id"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

// Hard delete. Scoped only by the same partition rule as every other
// query here — NOT restricted to developer-owned rows. An ADMIN/USER
// can hard-delete a real patient; a developer can hard-delete a
// developer-flagged one. Cascades to that patient's assignments
// (ON DELETE CASCADE), which in turn cascade to their results — see the
// header comment if real, permanent removal of clinical records isn't
// actually the intended behavior for the ADMIN/USER side of this.
func (q *Queries) DeletePatient(ctx context.Context, arg DeletePatientParams) error {
	_, err := q.db.Exec(ctx, deletePatient, arg.ID, arg.ViewerID)
	return err
}

const getPatient = `-- name: GetPatient :one

SELECT id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes FROM patients
WHERE id = $1
  AND is_developer_data = is_developer_user($2)
`

type GetPatientParams struct {
	ID       uuid.UUID `json:"id"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

// patients.sql
//
// sqlc queries for the patients table.
//
// Visibility/CRUD rule (see is_developer_data on the patients table,
// and the trigger that sets it): a strict partition, not "developers
// see everything" —
//
//	is_developer_data = is_developer_user(viewer_id)
//
// ADMIN/USER viewers only ever see, edit, or delete real patients
// (is_developer_data = FALSE). DEVELOPER viewers only ever see, edit,
// or delete developer-flagged patients (TRUE) — any developer, not
// just the one who created a given row, but NEVER real patient data.
// Neither role can reach into the other's universe, for any operation,
// including delete — this is deliberate, so a developer account used
// to debug in prod is structurally incapable of touching real patient
// data, not just discouraged from it.
//
// This is enforced at the query layer, not via a DB-level policy (no
// RLS) — every query below applies it explicitly, including writes, so
// a viewer can't reach a patient outside their partition by guessing/
// reusing an id either. That means it only protects you if every code
// path that touches `patients` goes through these queries.
//
// Both SetPatientActive (soft archive) and DeletePatient (hard delete)
// are unrestricted within a viewer's own partition — ADMIN/USER can
// freely hard-delete real patients, same as a developer can freely
// hard-delete their own team's test patients. Worth flagging since this
// removes any append-only/retention protection on real patient
// records: if that's not actually wanted for real clinical data, say so
// and DeletePatient can be scoped to developer-only instead, or
// dropped entirely in favor of SetPatientActive as the only removal path.
func (q *Queries) GetPatient(ctx context.Context, arg GetPatientParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, getPatient, arg.ID, arg.ViewerID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Mrn,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Sex,
		&i.CreatedBy,
		&i.IsDeveloperData,
		&i.IsActive,
		&i.ComputedStatus,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return &i, err
}

const getPatientByMRN = `-- name: GetPatientByMRN :one
SELECT id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes FROM patients
WHERE mrn = $1
  AND is_developer_data = is_developer_user($2)
`

type GetPatientByMRNParams struct {
	Mrn      string    `json:"mrn"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

// For intake lookups / duplicate-MRN checks before creating a new record.
func (q *Queries) GetPatientByMRN(ctx context.Context, arg GetPatientByMRNParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, getPatientByMRN, arg.Mrn, arg.ViewerID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Mrn,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Sex,
		&i.CreatedBy,
		&i.IsDeveloperData,
		&i.IsActive,
		&i.ComputedStatus,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return &i, err
}

const listPatients = `-- name: ListPatients :many
SELECT id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes FROM patients
WHERE is_active
  AND is_developer_data = is_developer_user($1)
ORDER BY full_name
LIMIT $3 OFFSET $2
`

type ListPatientsParams struct {
	ViewerID  uuid.UUID `json:"viewer_id"`
	RowOffset int32     `json:"row_offset"`
	RowLimit  int32     `json:"row_limit"`
}

// Main patient directory. Alphabetical by name; swap to
// last_activity_at DESC if the roster should read more like a worklist
// than a directory — a judgment call, easy to flip either way.
func (q *Queries) ListPatients(ctx context.Context, arg ListPatientsParams) ([]*Patient, error) {
	rows, err := q.db.Query(ctx, listPatients, arg.ViewerID, arg.RowOffset, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Mrn,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DateOfBirth,
			&i.Sex,
			&i.CreatedBy,
			&i.IsDeveloperData,
			&i.IsActive,
			&i.ComputedStatus,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatientsByStatus = `-- name: ListPatientsByStatus :many
SELECT id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes FROM patients
WHERE is_active
  AND computed_status = $1
  AND is_developer_data = is_developer_user($2)
ORDER BY last_activity_at DESC NULLS LAST
LIMIT $4 OFFSET $3
`

type ListPatientsByStatusParams struct {
	ComputedStatus *AssignmentStatus `json:"computed_status"`
	ViewerID       uuid.UUID         `json:"viewer_id"`
	RowOffset      int32             `json:"row_offset"`
	RowLimit       int32             `json:"row_limit"`
}

// e.g. everything currently READY_FOR_REVIEW, for a "needs your
// attention" view.
func (q *Queries) ListPatientsByStatus(ctx context.Context, arg ListPatientsByStatusParams) ([]*Patient, error) {
	rows, err := q.db.Query(ctx, listPatientsByStatus,
		arg.ComputedStatus,
		arg.ViewerID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Mrn,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DateOfBirth,
			&i.Sex,
			&i.CreatedBy,
			&i.IsDeveloperData,
			&i.IsActive,
			&i.ComputedStatus,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchPatients = `-- name: SearchPatients :many
SELECT id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes FROM patients
WHERE is_active
  AND is_developer_data = is_developer_user($1)
  AND (full_name ILIKE '%' || $2 || '%' OR mrn ILIKE '%' || $2 || '%')
ORDER BY full_name
LIMIT $3
`

type SearchPatientsParams struct {
	ViewerID uuid.UUID `json:"viewer_id"`
	Query    *string   `json:"query"`
	RowLimit int32     `json:"row_limit"`
}

// Matches the mockup's client-side search (name or id substring match),
// server-side. Uses the full_name trigram index; also matches on mrn
// for "type in the chart number" lookups.
func (q *Queries) SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]*Patient, error) {
	rows, err := q.db.Query(ctx, searchPatients, arg.ViewerID, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.Mrn,
			&i.FullName,
			&i.Email,
			&i.Phone,
			&i.DateOfBirth,
			&i.Sex,
			&i.CreatedBy,
			&i.IsDeveloperData,
			&i.IsActive,
			&i.ComputedStatus,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Notes,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPatientActive = `-- name: SetPatientActive :one
UPDATE patients
SET is_active = $2
WHERE id = $1
  AND is_developer_data = is_developer_user($3)
RETURNING id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes
`

type SetPatientActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
	ViewerID uuid.UUID `json:"viewer_id"`
}

// Archive/reactivate — the safe, reversible removal path.
func (q *Queries) SetPatientActive(ctx context.Context, arg SetPatientActiveParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, setPatientActive, arg.ID, arg.IsActive, arg.ViewerID)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Mrn,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Sex,
		&i.CreatedBy,
		&i.IsDeveloperData,
		&i.IsActive,
		&i.ComputedStatus,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return &i, err
}

const updatePatientDetails = `-- name: UpdatePatientDetails :one
UPDATE patients
SET
    full_name = $2,
    email = $3,
    phone = $4,
    date_of_birth = $5,
    sex = $6
WHERE id = $1
  AND is_developer_data = is_developer_user($7)
RETURNING id, mrn, full_name, email, phone, date_of_birth, sex, created_by, is_developer_data, is_active, computed_status, last_activity_at, created_at, updated_at, notes
`

type UpdatePatientDetailsParams struct {
	ID          uuid.UUID   `json:"id"`
	FullName    string      `json:"full_name"`
	Email       *string     `json:"email"`
	Phone       *string     `json:"phone"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Sex         *Sex        `json:"sex"`
	ViewerID    uuid.UUID   `json:"viewer_id"`
}

func (q *Queries) UpdatePatientDetails(ctx context.Context, arg UpdatePatientDetailsParams) (*Patient, error) {
	row := q.db.QueryRow(ctx, updatePatientDetails,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.Phone,
		arg.DateOfBirth,
		arg.Sex,
		arg.ViewerID,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.Mrn,
		&i.FullName,
		&i.Email,
		&i.Phone,
		&i.DateOfBirth,
		&i.Sex,
		&i.CreatedBy,
		&i.IsDeveloperData,
		&i.IsActive,
		&i.ComputedStatus,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Notes,
	)
	return &i, err
}
