// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pending_auth_challenges.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingAuthChallenge = `-- name: CreatePendingAuthChallenge :one
INSERT INTO pending_auth_challenges (
    id,
    user_id,
    mode,
    secret,
    remember_me,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, mode, secret, remember_me, expires_at, created_at
`

type CreatePendingAuthChallengeParams struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Mode       string             `json:"mode"`
	Secret     *string            `json:"secret"`
	RememberMe bool               `json:"remember_me"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePendingAuthChallenge(ctx context.Context, arg CreatePendingAuthChallengeParams) (*PendingAuthChallenge, error) {
	row := q.db.QueryRow(ctx, createPendingAuthChallenge,
		arg.ID,
		arg.UserID,
		arg.Mode,
		arg.Secret,
		arg.RememberMe,
		arg.ExpiresAt,
	)
	var i PendingAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Secret,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredPendingAuthChallenges = `-- name: DeleteExpiredPendingAuthChallenges :exec
DELETE FROM pending_auth_challenges
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredPendingAuthChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingAuthChallenges)
	return err
}

const deletePendingAuthChallenge = `-- name: DeletePendingAuthChallenge :exec
DELETE FROM pending_auth_challenges
WHERE id = $1
`

func (q *Queries) DeletePendingAuthChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingAuthChallenge, id)
	return err
}

const deletePendingAuthChallengesByUser = `-- name: DeletePendingAuthChallengesByUser :exec
DELETE FROM pending_auth_challenges
WHERE user_id = $1
  AND mode = $2
`

type DeletePendingAuthChallengesByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Mode   string    `json:"mode"`
}

func (q *Queries) DeletePendingAuthChallengesByUser(ctx context.Context, arg DeletePendingAuthChallengesByUserParams) error {
	_, err := q.db.Exec(ctx, deletePendingAuthChallengesByUser, arg.UserID, arg.Mode)
	return err
}

const getPendingAuthChallenge = `-- name: GetPendingAuthChallenge :one
SELECT id, user_id, mode, secret, remember_me, expires_at, created_at FROM pending_auth_challenges
WHERE id = $1
  AND expires_at > NOW()
`

func (q *Queries) GetPendingAuthChallenge(ctx context.Context, id uuid.UUID) (*PendingAuthChallenge, error) {
	row := q.db.QueryRow(ctx, getPendingAuthChallenge, id)
	var i PendingAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Secret,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getPendingAuthChallengeByUser = `-- name: GetPendingAuthChallengeByUser :one
SELECT id, user_id, mode, secret, remember_me, expires_at, created_at FROM pending_auth_challenges
WHERE user_id = $1
  AND mode = $2
  AND expires_at > NOW()
`

type GetPendingAuthChallengeByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Mode   string    `json:"mode"`
}

func (q *Queries) GetPendingAuthChallengeByUser(ctx context.Context, arg GetPendingAuthChallengeByUserParams) (*PendingAuthChallenge, error) {
	row := q.db.QueryRow(ctx, getPendingAuthChallengeByUser, arg.UserID, arg.Mode)
	var i PendingAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Secret,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const promoteChallengeToRegistration = `-- name: PromoteChallengeToRegistration :one
UPDATE pending_auth_challenges
SET
    mode   = 'totp_registration',
    secret = $2
WHERE id = $1
    AND mode = 'mfa_challenge'
    AND expires_at > NOW()
RETURNING id, user_id, mode, secret, remember_me, expires_at, created_at
`

type PromoteChallengeToRegistrationParams struct {
	ID     uuid.UUID `json:"id"`
	Secret *string   `json:"secret"`
}

func (q *Queries) PromoteChallengeToRegistration(ctx context.Context, arg PromoteChallengeToRegistrationParams) (*PendingAuthChallenge, error) {
	row := q.db.QueryRow(ctx, promoteChallengeToRegistration, arg.ID, arg.Secret)
	var i PendingAuthChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Mode,
		&i.Secret,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}
