// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupExpiredEmailVerifications(ctx context.Context) error
	CleanupExpiredPasswordResets(ctx context.Context) error
	CleanupInactiveUsers(ctx context.Context) error
	// A clinician confirming the review — reviewer_id doubles as both
	// "who reviewed this" and "who's asking" for the partition check, since
	// in every real flow they're the same person.
	CompleteAssignmentReview(ctx context.Context, arg CompleteAssignmentReviewParams) (*Assignment, error)
	// Patient-facing: marks the token used at the moment they actually
	// start/submit their assessment. Re-checks validity in the same
	// statement (not just relying on a prior GetRemoteAccessTokenByHash
	// call) to close the race where two requests redeem the same link at
	// once — only one can win. Returns zero rows if it was already
	// used/revoked/expired between the two calls.
	ConsumeRemoteAccessToken(ctx context.Context, tokenHash string) (*RemoteAccessToken, error)
	// For a small "N active tests" badge on a patient's row/header.
	CountActiveAssignmentsForPatient(ctx context.Context, arg CountActiveAssignmentsForPatientParams) (int64, error)
	// Backs a dashboard "Active patients" stat. For a developer viewer,
	// this counts only their team's developer-flagged patients — real
	// patients are entirely outside a developer's view, by design.
	CountActivePatients(ctx context.Context, viewerID uuid.UUID) (int64, error)
	// Backs the dashboard's "Awaiting review" stat card.
	CountAssignmentsAwaitingReview(ctx context.Context, viewerID uuid.UUID) (int64, error)
	// Backs the dashboard's "Completed (7d)"-style stat card; pass
	// NOW() - INTERVAL '7 days' (or whatever window) as $1.
	CountAssignmentsCompletedSince(ctx context.Context, arg CountAssignmentsCompletedSinceParams) (int64, error)
	// Backs the dashboard's "In progress" stat card.
	CountAssignmentsInProgress(ctx context.Context, viewerID uuid.UUID) (int64, error)
	// For a small "3 reminders sent" badge/tooltip.
	CountRemindersForAssignment(ctx context.Context, arg CountRemindersForAssignmentParams) (int64, error)
	CountRoles(ctx context.Context) (int64, error)
	// How many assignments reference this instrument. The Developer CRUD
	// screen should call this before offering a hard delete — a non-zero
	// count means DeleteTestDefinition will fail on the FK, and the UI
	// should steer toward SetTestDefinitionActive(false) instead.
	CountTestDefinitionAssignments(ctx context.Context, testCode string) (int64, error)
	CountUnusedBackupCodesForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	// is_developer_data is NOT a column here — stamped automatically by
	// trigger_mark_assignment_developer_data based on assigned_by's role.
	// Also implicitly needs a matching assignment_results envelope row —
	// see CreateAssignmentResult in assignment_results.sql, called
	// immediately after this in the same transaction (kept as two queries,
	// not one, since assignment_results.sql owns that table's shape).
	CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (*Assignment, error)
	// assignment_reminders.sql
	//
	// sqlc queries for the assignment_reminders table — just an audit trail
	// of "Send reminder" events, no scoring/state-machine logic here.
	//
	// Same inherited-partition pattern as remote_access_tokens.sql (this
	// table has no is_developer_data column of its own; visibility comes
	// via join to assignments/patients):
	//     (a.is_developer_data OR p.is_developer_data) = is_developer_user(viewer_id)
	// applies to the staff-facing queries (CreateAssignmentReminder and the
	// list/count/throttle-check reads).
	//
	// ListAssignmentsDueForReminder is different from every other query in
	// this file: it's meant to be called by a scheduled job, not a logged-
	// in staff member, so there's no viewer_id to check against — same
	// reasoning as MarkAssignmentReadyForReview in assignments.sql. But
	// unlike that query, this one still can't just skip the partition
	// question entirely: an automated job blasting reminder emails should
	// never pick up developer test assignments (which likely don't even
	// have real email addresses behind them), so it hard-excludes
	// is_developer_data rows unconditionally, rather than gating on who's
	// asking.
	//
	// sent_by is nullable on the table itself specifically so this file can
	// distinguish a human-initiated reminder from a scheduled one — see
	// CreateAssignmentReminder vs CreateSystemAssignmentReminder.
	// A staff member clicking "Send reminder". sent_by is the clicking
	// user, who also doubles as the viewer for the partition check (same
	// reasoning as reviewer_id in assignments.CompleteAssignmentReview).
	CreateAssignmentReminder(ctx context.Context, arg CreateAssignmentReminderParams) (*AssignmentReminder, error)
	// assignment_results.sql
	//
	// sqlc queries covering all four results-related tables:
	//   assignment_results          (generic envelope: responses, raw_scores,
	//                                 duration_seconds, scored_at)
	//   assignment_sum_band_results (SUM_BANDED display fields — ASQ/BAI/BDI/P3)
	//   assignment_mmpi_scales      (MMPI category/scale/subscale tree)
	//   assignment_mmpi_indications (MMPI per-category narrative bullets)
	//
	// Write/read split, different from patients.sql/assignments.sql:
	//
	//   WRITE queries here (UpdateAssignmentResponses,
	//   FinalizeAssignmentResultScoring, CreateSumBandResult,
	//   CreateMMPIScales, CreateMMPIIndications) have NO viewer_id/partition
	//   check. These aren't a clinician managing a record through the app's
	//   role system — they're the answer-submission and scoring pipeline
	//   itself: a patient answering (remote via a redeemed token, or
	//   in-clinic on a handed-over device) and the scoring engine writing
	//   the outcome once every item is in. There's no meaningful "viewer"
	//   in either of those code paths, same reasoning as
	//   MarkAssignmentReadyForReview in assignments.sql. They're keyed
	//   purely by assignment_id / assignment_result_id, which the calling
	//   code already resolved through a trusted path (a consumed
	//   remote_access_token, or an assignment a staff member is actively
	//   administering in-clinic).
	//
	//   CreateAssignmentResult is the one exception — it's paired 1:1 with
	//   assignments.CreateAssignment, which IS a staff-initiated action, so
	//   it carries the same viewer_id guard for consistency with that call.
	//
	//   READ queries (GetAssignmentResult, GetSumBandResultForAssignment,
	//   ListMMPIScalesForResult, ListMMPIIndicationsForResult) are exactly
	//   what a clinician browses in the UI, so these DO carry the usual
	//   inherited partition check:
	//       (a.is_developer_data OR p.is_developer_data) = is_developer_user(viewer_id)
	//
	// CreateMMPIScales / CreateMMPIIndications are bulk inserts (a whole
	// category/scale tree, or a whole set of indications, in one round
	// trip) using jsonb_to_recordset() over a single JSONB array parameter.
	//
	// An earlier version of this file used unnest() over N parallel array
	// parameters instead. That's invalid for sqlc's own built-in query
	// analyzer (the one used without a live Postgres connection for type-
	// checking): `unnest(a, b, c, ...)` with multiple arguments in a FROM
	// clause is special-cased PARSER behavior in real Postgres — it zips
	// the arrays into rows — not a literal function overload sitting in
	// pg_catalog that takes N arguments. sqlc's analyzer does a plain
	// "does a function with this name/arity exist" lookup and finds
	// nothing, hence `function unnest(unknown, unknown, ...) does not
	// exist`. jsonb_to_recordset() is an ordinary single-argument function,
	// so it doesn't hit that gap — and it's arguably safer anyway: one
	// JSON blob instead of N same-length arrays that could silently drift
	// out of sync with each other.
	//
	// For assignment_mmpi_scales, self-referencing parent_scale_id works
	// fine even when a parent and its subscales are inserted in the very
	// same statement: for a NOT DEFERRABLE foreign key (the default, used
	// throughout this schema), Postgres checks the constraint once at the
	// END of the statement, after every row from it is already in the
	// table — not per-row as each is inserted. So a subscale's
	// parent_scale_id can reference a sibling row from the same batch
	// regardless of its position in the JSON array. (Verified against
	// Postgres's documented FK check timing, not assumed.)
	//
	// Also included: GetAssignmentResultForTaking (the patient-facing
	// counterpart to UpdateAssignmentResponses — fetching progress, not
	// just writing it) and ListScaleScoreHistoryForPatient (the scale-trend
	// query assignment_mmpi_scales' schema comment promised but was never
	// actually written).
	// Paired with assignments.CreateAssignment, same transaction, same
	// actor as viewer_id. responses starts empty; everything else stays
	// NULL until the patient answers and the engine scores it.
	CreateAssignmentResult(ctx context.Context, arg CreateAssignmentResultParams) (*AssignmentResult, error)
	CreateBackupCodes(ctx context.Context, arg CreateBackupCodesParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (*CreateEmailVerificationRow, error)
	// Bulk insert for one MMPI result's full set of per-category narrative
	// indications. Same jsonb_to_recordset() pattern as CreateMMPIScales —
	// sqlc.arg(indications) is a single JSONB array, one object per
	// indication line. No viewer_id — see header comment.
	CreateMMPIIndications(ctx context.Context, indications []byte) ([]*AssignmentMmpiIndication, error)
	// Bulk insert for one MMPI result's full category/scale/subscale tree
	// in one round trip. sqlc.arg(scales) is a single JSONB array
	// parameter, one object per scale/subscale row, e.g.:
	//   [
	//     {"id": "...", "assignment_result_id": "...", "parent_scale_id": null,
	//      "category_title": "Validity Scales", "scale_code": "VRIN",
	//      "scale_name": "VRIN", "scale_description": "...", "scale_purpose": "...",
	//      "raw_score": 3, "score": 45, "display_order": 0},
	//     ...
	//   ]
	// Position within the array doesn't matter FK-wise — see header comment
	// on why the self-reference is safe within one statement regardless of
	// ordering. No viewer_id — see header comment.
	CreateMMPIScales(ctx context.Context, scales []byte) ([]*AssignmentMmpiScale, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (*CreatePasswordResetRow, error)
	// is_developer_data is NOT a column here — it's stamped automatically
	// by trigger_mark_patient_developer_data based on created_by's role, so
	// there's no path for the app to get this wrong or forget to set it,
	// and no path for a real user to accidentally create a patient that
	// lands in the developer partition or vice versa.
	CreatePatient(ctx context.Context, arg CreatePatientParams) (*Patient, error)
	CreatePendingAuthChallenge(ctx context.Context, arg CreatePendingAuthChallengeParams) (*PendingAuthChallenge, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (*Role, error)
	// The SUM_BANDED-specific display fields (ASQ/BAI/BDI/P3). Called right
	// after FinalizeAssignmentResultScoring for those tests only — MMPI
	// results use CreateMMPIScales/CreateMMPIIndications instead. No
	// viewer_id — see header comment.
	CreateSumBandResult(ctx context.Context, arg CreateSumBandResultParams) (*AssignmentSumBandResult, error)
	// A scheduled job's automated reminder — sent_by is left NULL (no
	// human triggered this), and there's deliberately no partition check
	// here: by the time this is called, the assignment_id already came from
	// ListAssignmentsDueForReminder, which already excluded developer data.
	CreateSystemAssignmentReminder(ctx context.Context, arg CreateSystemAssignmentReminderParams) (*AssignmentReminder, error)
	// Adds a new instrument row after its JSON file has been authored and
	// placed at source_path. version starts at 1; is_active defaults to
	// TRUE (a newly-added instrument should be immediately assignable
	// unless the Developer explicitly deactivates it).
	CreateTestDefinition(ctx context.Context, arg CreateTestDefinitionParams) (*CreateTestDefinitionRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (*Session, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteAllRoles(ctx context.Context) error
	// Hard delete, no status restriction — scoped only by the same
	// partition rule as every other query here, NOT developer-only. Same
	// flag as patients.DeletePatient: this removes any append-only/
	// retention protection on real assignment/result history if that
	// matters for real clinical data.
	DeleteAssignment(ctx context.Context, arg DeleteAssignmentParams) error
	DeleteEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteExpiredPendingAuthChallenges(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePasswordResetByUserID(ctx context.Context, userID uuid.UUID) error
	// Hard delete. Scoped only by the same partition rule as every other
	// query here — NOT restricted to developer-owned rows. An ADMIN/USER
	// can hard-delete a real patient; a developer can hard-delete a
	// developer-flagged one. Cascades to that patient's assignments
	// (ON DELETE CASCADE), which in turn cascade to their results — see the
	// header comment if real, permanent removal of clinical records isn't
	// actually the intended behavior for the ADMIN/USER side of this.
	DeletePatient(ctx context.Context, arg DeletePatientParams) error
	DeletePendingAuthChallenge(ctx context.Context, id uuid.UUID) error
	DeletePendingAuthChallengesByUser(ctx context.Context, arg DeletePendingAuthChallengesByUserParams) error
	DeleteRole(ctx context.Context, id string) error
	// Hard delete. Will raise a foreign key violation if any assignment
	// has ever referenced this code (assignments.test_code is
	// ON DELETE RESTRICT, intentionally — deleting an instrument out from
	// under historical results would silently corrupt them). Only safe to
	// call when CountTestDefinitionAssignments returns 0; otherwise use
	// SetTestDefinitionActive to retire it instead.
	DeleteTestDefinition(ctx context.Context, code string) error
	// Safe, reversible-in-spirit correction path for a real mistake (wrong
	// test assigned to the wrong patient). Restricted to status =
	// 'ASSIGNED': once a patient has answered even one item, use
	// DeleteAssignment instead, which has no such restriction. Unrestricted
	// by role beyond the usual partition check — any ADMIN/USER can use
	// this on a real assignment, any developer on a developer-flagged one.
	DeleteUnstartedAssignment(ctx context.Context, arg DeleteUnstartedAssignmentParams) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserBackupCodes(ctx context.Context, userID uuid.UUID) error
	DisableUser2FA(ctx context.Context, id uuid.UUID) error
	EnableUser2FA(ctx context.Context, arg EnableUser2FAParams) error
	ExistDeveloperAccount(ctx context.Context) (bool, error)
	ExistsUserWithEmail(ctx context.Context, email string) (bool, error)
	ExistsUserWithUsername(ctx context.Context, username string) (bool, error)
	// Called by the scoring engine once every item is answered, before it
	// writes the engine-specific rows below. Generic to both SUM_BANDED and
	// MULTISCALE_PROFILE. duration_seconds per the server-timestamp-only
	// mechanism discussed separately (assignment_page_timings). No
	// viewer_id — see header comment.
	FinalizeAssignmentResultScoring(ctx context.Context, arg FinalizeAssignmentResultScoringParams) (*AssignmentResult, error)
	// The currently usable token for an assignment, if any — backs a "link
	// sent 2 days ago, expires in 5 days" display, and lets the app decide
	// whether a "Send" or "Resend" action is appropriate.
	GetActiveRemoteAccessToken(ctx context.Context, arg GetActiveRemoteAccessTokenParams) (*RemoteAccessToken, error)
	GetActiveSession(ctx context.Context, sessionTokenHash string) (*GetActiveSessionRow, error)
	GetActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]*Session, error)
	// assignments.sql
	//
	// sqlc queries for the assignments table.
	//
	// Visibility/CRUD rule — same strict partition as patients.sql:
	//     (a.is_developer_data OR p.is_developer_data) = is_developer_user(viewer_id)
	// An assignment is in the developer partition if EITHER the assignment
	// itself OR its patient is developer-flagged (a developer can create a
	// throwaway assignment against an otherwise-real, ADMIN/USER-visible
	// patient — that assignment alone still belongs entirely to the
	// developer partition). ADMIN/USER viewers only ever see/manage
	// assignments fully outside that partition; DEVELOPER viewers only
	// ever see/manage assignments inside it. Every query below joins
	// patients as `p` for this reason, even ones that don't otherwise need
	// patient columns — one uniform predicate shape across the whole file.
	//
	// Status lifecycle assumed here: ASSIGNED -> IN_PROGRESS (auto, on
	// first response — see mark_assignment_started_on_response trigger) ->
	// READY_FOR_REVIEW (set by the app once the scoring engine finishes
	// scoring all responses) -> COMPLETED (set once a clinician confirms
	// the review). "Overdue" is not a status value — it's
	// (due_at < now() AND status <> 'COMPLETED'), same as the partial index
	// on assignments(due_at).
	//
	// MarkAssignmentReadyForReview is the one write query here WITHOUT a
	// viewer/partition check: it's called by the scoring pipeline itself
	// right after computing scores, not by a user clicking something in the
	// UI, so there's no "viewer" to check against — it should transition
	// any assignment, real or developer-flagged, accurately.
	//
	// Both DeleteUnstartedAssignment and DeleteAssignment are unrestricted
	// within a viewer's own partition (no developer-only carve-out) — see
	// patients.sql's header comment for the same flag on DeletePatient.
	GetAssignment(ctx context.Context, arg GetAssignmentParams) (*Assignment, error)
	GetAssignmentResult(ctx context.Context, arg GetAssignmentResultParams) (*AssignmentResult, error)
	// Patient-facing: fetch current responses/progress to resume an
	// in-progress assessment (remote or in-clinic). No viewer_id — see
	// header comment.
	GetAssignmentResultForTaking(ctx context.Context, assignmentID uuid.UUID) (*AssignmentResult, error)
	GetBackupCodeByHash(ctx context.Context, codeHash string) (*GetBackupCodeByHashRow, error)
	GetEmailVerificationByID(ctx context.Context, id uuid.UUID) (*GetEmailVerificationByIDRow, error)
	GetEmailVerificationByToken(ctx context.Context, token string) (*GetEmailVerificationByTokenRow, error)
	GetEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) (*GetEmailVerificationByUserIDRow, error)
	// For a UI throttle ("last reminder sent 2h ago, try again after 24h")
	// or to decide whether to grey out the "Send reminder" button. NULL if
	// none have ever been sent.
	GetLastReminderSentAt(ctx context.Context, arg GetLastReminderSentAtParams) (pgtype.Timestamptz, error)
	GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error)
	GetPasswordResetByToken(ctx context.Context, token string) (*PasswordReset, error)
	// patients.sql
	//
	// sqlc queries for the patients table.
	//
	// Visibility/CRUD rule (see is_developer_data on the patients table,
	// and the trigger that sets it): a strict partition, not "developers
	// see everything" —
	//     is_developer_data = is_developer_user(viewer_id)
	// ADMIN/USER viewers only ever see, edit, or delete real patients
	// (is_developer_data = FALSE). DEVELOPER viewers only ever see, edit,
	// or delete developer-flagged patients (TRUE) — any developer, not
	// just the one who created a given row, but NEVER real patient data.
	// Neither role can reach into the other's universe, for any operation,
	// including delete — this is deliberate, so a developer account used
	// to debug in prod is structurally incapable of touching real patient
	// data, not just discouraged from it.
	//
	// This is enforced at the query layer, not via a DB-level policy (no
	// RLS) — every query below applies it explicitly, including writes, so
	// a viewer can't reach a patient outside their partition by guessing/
	// reusing an id either. That means it only protects you if every code
	// path that touches `patients` goes through these queries.
	//
	// Both SetPatientActive (soft archive) and DeletePatient (hard delete)
	// are unrestricted within a viewer's own partition — ADMIN/USER can
	// freely hard-delete real patients, same as a developer can freely
	// hard-delete their own team's test patients. Worth flagging since this
	// removes any append-only/retention protection on real patient
	// records: if that's not actually wanted for real clinical data, say so
	// and DeletePatient can be scoped to developer-only instead, or
	// dropped entirely in favor of SetPatientActive as the only removal path.
	GetPatient(ctx context.Context, arg GetPatientParams) (*Patient, error)
	// For intake lookups / duplicate-MRN checks before creating a new record.
	GetPatientByMRN(ctx context.Context, arg GetPatientByMRNParams) (*Patient, error)
	GetPendingAuthChallenge(ctx context.Context, id uuid.UUID) (*PendingAuthChallenge, error)
	GetPendingAuthChallengeByUser(ctx context.Context, arg GetPendingAuthChallengeByUserParams) (*PendingAuthChallenge, error)
	// Patient-facing: looks up the token the patient's link decoded to
	// (already hashed by the app before this query runs — never look up by
	// raw token). No viewer_id — see header comment. Only returns a row if
	// the token is actually still usable; an expired/used/revoked token
	// simply doesn't match, which the app should treat as "this link is no
	// longer valid" without distinguishing why.
	GetRemoteAccessTokenByHash(ctx context.Context, tokenHash string) (*RemoteAccessToken, error)
	GetRoleByID(ctx context.Context, id string) (*Role, error)
	GetRoleById(ctx context.Context, id string) (*Role, error)
	// The single most useful read for rendering a SUM_BANDED result screen:
	// joins straight from assignment_id to the envelope and the display
	// fields, no need to look up assignment_result_id first.
	GetSumBandResultForAssignment(ctx context.Context, arg GetSumBandResultForAssignmentParams) (*GetSumBandResultForAssignmentRow, error)
	// test_definitions.sql
	//
	// sqlc queries for the test_definitions table (the instrument catalog).
	// Covers two consumers:
	//   1. The clinician-facing "Test catalog" view from the mockup (grid
	//      of active instruments, click-through to a detail view) and the
	//      test picker used when assigning a test to a patient.
	//   2. A Developer-role CRUD screen for managing the catalog itself —
	//      not shown in the mockup, but requested up front, so the create/
	//      update/delete/reactivate shapes below are built for that now
	//      rather than bolted on later.
	//
	// Future-proofing notes:
	//   - List queries take LIMIT/OFFSET even though the catalog is small
	//     today (4-5 rows) — cheap to include now, and a Developer CRUD
	//     screen listing every instrument (active + inactive) is exactly
	//     the kind of view that quietly grows over time.
	//   - "Metadata" edits (name/domain/scoring_method/requires_sex/
	//     item_count/typical_duration_minutes) are a separate query from
	//     "source" refreshes (source_path/source_checksum/version). These
	//     are two different workflows in the Developer UI — editing catalog
	//     facts by hand vs. re-importing a JSON file — and conflating them
	//     would make it easy to accidentally bump `version` on a plain
	//     metadata edit, or vice versa.
	//   - `code` is intentionally never updatable (it's the FK target for
	//     assignments.test_code). If a code genuinely needs to change,
	//     that's a new row + migrating assignments, not an UPDATE.
	//   - DeleteTestDefinition is a real hard delete, left in for
	//     completeness, but assignments.test_code has ON DELETE RESTRICT —
	//     it will fail with a foreign key violation for any instrument
	//     that's ever been assigned. CountTestDefinitionAssignments exists
	//     so the Developer UI can check this up front and steer the user
	//     toward SetTestDefinitionActive (soft retire) instead of letting
	//     them hit a raw DB error.
	// Full row for one instrument. Used for the catalog detail view and by
	// the assignment flow to check is_active/requires_sex/scoring_method
	// before letting a clinician assign it.
	GetTestDefinition(ctx context.Context, code string) (*TestDefinition, error)
	GetUnusedBackupCodesForUser(ctx context.Context, userID uuid.UUID) ([]*GetUnusedBackupCodesForUserRow, error)
	GetUser2FASecret(ctx context.Context, id uuid.UUID) (*GetUser2FASecretRow, error)
	GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (*GetUserByEmailOrUsernameRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*GetUserByIDRow, error)
	GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error)
	GetUserCountBySearch(ctx context.Context, arg GetUserCountBySearchParams) (int64, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]*GetUsersRow, error)
	GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]*GetUsersByRoleRow, error)
	GetUsersByRoleCount(ctx context.Context, role string) (int64, error)
	GetUsersCount(ctx context.Context) (int64, error)
	// One assignment's full history (created, started, ready for review,
	// reviewed, links sent, reminders sent), most recent first.
	ListActivityForAssignment(ctx context.Context, arg ListActivityForAssignmentParams) ([]*ListActivityForAssignmentRow, error)
	// One patient's timeline (patient detail view), most recent first.
	ListActivityForPatient(ctx context.Context, arg ListActivityForPatientParams) ([]*ListActivityForPatientRow, error)
	// Dashboard-wide "needs your attention" list, oldest-waiting-first.
	// Joins patient name too, since this spans multiple patients. For a
	// developer viewer, this is scoped entirely to their team's test
	// assignments, same as everything else in this file.
	ListAssignmentsAwaitingReview(ctx context.Context, arg ListAssignmentsAwaitingReviewParams) ([]*ListAssignmentsAwaitingReviewRow, error)
	// For a scheduled job: not-yet-completed assignments due on or before
	// sqlc.arg(due_before), whose most recent reminder (if any) is older
	// than sqlc.arg(reminder_cutoff) — i.e. either never reminded, or not
	// reminded recently enough to remind again. Always excludes developer
	// test data (see header comment) regardless of who/what calls this.
	ListAssignmentsDueForReminder(ctx context.Context, arg ListAssignmentsDueForReminderParams) ([]*ListAssignmentsDueForReminderRow, error)
	// Powers the patient detail view's assignment list. Joins
	// test_definitions for display name so the UI doesn't need a second
	// round trip per row.
	ListAssignmentsForPatient(ctx context.Context, arg ListAssignmentsForPatientParams) ([]*ListAssignmentsForPatientRow, error)
	// Backs the patient detail view's status filter tabs (In progress /
	// Ready to review / Complete). For the "Overdue" tab, use
	// ListOverdueAssignmentsForPatient instead — overdue cuts across
	// multiple statuses, it isn't one itself.
	ListAssignmentsForPatientByStatus(ctx context.Context, arg ListAssignmentsForPatientByStatusParams) ([]*ListAssignmentsForPatientByStatusRow, error)
	ListMMPIIndicationsForResult(ctx context.Context, arg ListMMPIIndicationsForResultParams) ([]*AssignmentMmpiIndication, error)
	// Flat, ordered fetch of every scale/subscale row for one result. The
	// app reconstructs the category/parent-child tree client-side from
	// category_title + parent_scale_id + id — display_order already
	// reflects the intended render sequence.
	ListMMPIScalesForResult(ctx context.Context, arg ListMMPIScalesForResultParams) ([]*AssignmentMmpiScale, error)
	// Dashboard-wide overdue list, same shape as ListAssignmentsAwaitingReview.
	ListOverdueAssignments(ctx context.Context, arg ListOverdueAssignmentsParams) ([]*ListOverdueAssignmentsRow, error)
	ListOverdueAssignmentsForPatient(ctx context.Context, arg ListOverdueAssignmentsForPatientParams) ([]*ListOverdueAssignmentsForPatientRow, error)
	// Main patient directory. Alphabetical by name; swap to
	// last_activity_at DESC if the roster should read more like a worklist
	// than a directory — a judgment call, easy to flip either way.
	ListPatients(ctx context.Context, arg ListPatientsParams) ([]*Patient, error)
	// e.g. everything currently READY_FOR_REVIEW, for a "needs your
	// attention" view.
	ListPatientsByStatus(ctx context.Context, arg ListPatientsByStatusParams) ([]*Patient, error)
	// Dashboard-wide "Recent activity" feed, most recent first.
	ListRecentActivity(ctx context.Context, arg ListRecentActivityParams) ([]*ListRecentActivityRow, error)
	// Audit trail for one assignment. sent_by NULL means it was an
	// automated reminder, not a specific staff member's click.
	ListRemindersForAssignment(ctx context.Context, arg ListRemindersForAssignmentParams) ([]*AssignmentReminder, error)
	// Full send/resend history for an assignment (audit trail — "link sent,
	// then resent twice, then used").
	ListRemoteAccessTokensForAssignment(ctx context.Context, arg ListRemoteAccessTokensForAssignmentParams) ([]*RemoteAccessToken, error)
	ListRoles(ctx context.Context) ([]*Role, error)
	// One scale's score across every MMPI assignment a patient has ever
	// had, oldest first — for a "D scale over time" trend chart. This is
	// the query assignment_mmpi_scales' schema comment promised ("useful
	// for trending a single scale... over time") but that was never
	// actually written until now.
	ListScaleScoreHistoryForPatient(ctx context.Context, arg ListScaleScoreHistoryForPatientParams) ([]*ListScaleScoreHistoryForPatientRow, error)
	ListTestDefinitions(ctx context.Context, arg ListTestDefinitionsParams) ([]*ListTestDefinitionsRow, error)
	// activity_events.sql
	//
	// sqlc queries for the activity_events table.
	//
	// Unlike every other file in this set, this table is populated almost
	// entirely by triggers (trigger_log_patient_created,
	// trigger_log_patient_active_changed, trigger_log_assignment_events,
	// trigger_log_link_sent, trigger_log_reminder_sent — see the migration),
	// all funneling through the shared log_activity_event() function. There
	// isn't a "CreateActivityEvent" query here for the app to call directly
	// with raw columns; LogActivityEvent below just calls that same shared
	// function, so any manual/ad-hoc event the app wants to record gets
	// exactly the same is_developer_data + actor_id handling as every
	// trigger-generated one, rather than a second, possibly-diverging
	// implementation of that logic.
	//
	// Visibility: is_developer_data lives directly ON this table (stamped
	// once at write time — see the column comment in the migration for
	// why), not derived via a join at read time. So the partition check
	// here is just a plain column comparison, no join required for
	// correctness:
	//     is_developer_data = is_developer_user(viewer_id)
	// The LEFT JOINs to patients/assignments/users in the list queries
	// below are purely for display (patient name, test name, actor name) —
	// all nullable, since a referenced patient/assignment/user may have
	// since been deleted while the event itself persists as history.
	// For any event the app wants to record that isn't already covered by
	// a trigger. Delegates entirely to log_activity_event(), so
	// is_developer_data and actor_id are computed identically to every
	// trigger-driven row.
	LogActivityEvent(ctx context.Context, arg LogActivityEventParams) error
	// Called by the scoring pipeline once every response is in and scored —
	// see the header comment for why this skips the viewer/partition check.
	// Guarded by the current status so it can't be called out of order
	// (e.g. twice, or on something already COMPLETED).
	MarkAssignmentReadyForReview(ctx context.Context, id uuid.UUID) (*Assignment, error)
	MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error
	MarkEmailVerificationUsed(ctx context.Context, token string) error
	MarkPasswordResetUsed(ctx context.Context, token string) error
	PromoteChallengeToRegistration(ctx context.Context, arg PromoteChallengeToRegistrationParams) (*PendingAuthChallenge, error)
	ReactivateUser(ctx context.Context, id uuid.UUID) error
	// Called after re-importing an instrument's JSON file (content changed,
	// even if the catalog metadata above didn't). Always bumps `version` by
	// 1, so a Developer glancing at the row can tell the file was
	// re-imported without needing to diff checksums by hand.
	RefreshTestDefinitionSource(ctx context.Context, arg RefreshTestDefinitionSourceParams) (*TestDefinition, error)
	// "Resend link" action: atomically revokes the current active token (if
	// any) and issues a new one, carrying resend_count forward + 1. If
	// there's no active token to revoke (e.g. it already expired), this
	// still issues a fresh one at resend_count 0 — a resend on an already-
	// lapsed link is effectively a new send.
	ResendRemoteAccessToken(ctx context.Context, arg ResendRemoteAccessTokenParams) (*RemoteAccessToken, error)
	// Standalone "invalidate this link" action (e.g. patient reports the
	// email was compromised), independent of sending a replacement.
	RevokeActiveRemoteAccessToken(ctx context.Context, arg RevokeActiveRemoteAccessTokenParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeAllUserSessionsExcept(ctx context.Context, arg RevokeAllUserSessionsExceptParams) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	RevokeSessionByHash(ctx context.Context, sessionTokenHash string) error
	// Matches the top-nav search bar's placeholder text ("Search patients,
	// tests…"), which isn't actually wired to anything in the static
	// mockup yet. Trigram/ILIKE match on name or code so it works for
	// partial, misspelled, or code-only queries (e.g. typing "bdi").
	SearchActiveTestDefinitions(ctx context.Context, arg SearchActiveTestDefinitionsParams) ([]*TestDefinition, error)
	// Matches the mockup's client-side search (name or id substring match),
	// server-side. Uses the full_name trigram index; also matches on mrn
	// for "type in the chart number" lookups.
	SearchPatients(ctx context.Context, arg SearchPatientsParams) ([]*Patient, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]*SearchUsersRow, error)
	// remote_access_tokens.sql
	//
	// sqlc queries for the remote_access_tokens table.
	//
	// Two different access models in this one file:
	//
	// 1. Staff-facing queries (send/resend/revoke/list/get-active) are used
	//    by an authenticated clinician or developer through the app, so
	//    they carry the same partition rule as patients.sql/assignments.sql
	//    — inherited via join, since this table has no is_developer_data
	//    column of its own:
	//        (a.is_developer_data OR p.is_developer_data) = is_developer_user(viewer_id)
	//
	// 2. Patient-facing queries (GetRemoteAccessTokenByHash,
	//    ConsumeRemoteAccessToken) are used by a patient who followed a
	//    secret emailed link — there's no logged-in app user/role in that
	//    flow at all, so there's deliberately NO viewer_id or partition
	//    check on these two. Validity is entirely about the token itself
	//    (unused, unrevoked, unexpired), same idea as
	//    MarkAssignmentReadyForReview having no viewer check in
	//    assignments.sql — no human "viewer" exists in that code path to
	//    check against.
	//
	// Only one usable ("active") token can exist per assignment at a time —
	// enforced by idx_remote_access_tokens_active (a partial unique index
	// on assignment_id WHERE used_at IS NULL AND NOT revoked). That's why
	// ResendRemoteAccessToken revokes the current active token and inserts
	// the replacement in one atomic statement (a writable CTE) — doing it
	// as two round trips would risk a moment where either both or neither
	// token is active.
	// Initial "Send link" action — there should be no existing active token
	// yet. If one exists, the unique partial index rejects this with a
	// constraint violation; the app should have already checked via
	// GetActiveRemoteAccessToken and called ResendRemoteAccessToken instead.
	SendRemoteAccessToken(ctx context.Context, arg SendRemoteAccessTokenParams) (*RemoteAccessToken, error)
	// Archive/reactivate — the safe, reversible removal path.
	SetPatientActive(ctx context.Context, arg SetPatientActiveParams) (*Patient, error)
	// Retire/reactivate toggle — a quick action on the CRUD screen's list
	// (e.g. a switch on each row), separate from the full edit form. Retiring
	// an instrument doesn't touch its history: existing assignments and
	// results referencing this code are untouched, it just stops appearing
	// in ListActiveTestDefinitions and can't be picked for new assignments.
	SetTestDefinitionActive(ctx context.Context, arg SetTestDefinitionActiveParams) (*TestDefinition, error)
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateAssignmentDueDate(ctx context.Context, arg UpdateAssignmentDueDateParams) (*Assignment, error)
	// Merges newly-answered items into responses (item_key -> answer).
	// Fires mark_assignment_started_on_response (assignments.sql's header
	// comment) as a side effect — that trigger flips ASSIGNED -> IN_PROGRESS
	// and sets started_at the first time this runs for an assignment.
	// No viewer_id — see header comment.
	UpdateAssignmentResponses(ctx context.Context, arg UpdateAssignmentResponsesParams) (*AssignmentResult, error)
	UpdatePatientDetails(ctx context.Context, arg UpdatePatientDetailsParams) (*Patient, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (*Role, error)
	// Edits the catalog-facing facts a Developer would change by hand in
	// the CRUD screen. Deliberately excludes `code` (immutable) and the
	// source_path/source_checksum/version trio (see RefreshTestDefinitionSource) —
	// these are two different edit workflows in the UI, not one form.
	UpdateTestDefinitionMetadata(ctx context.Context, arg UpdateTestDefinitionMetadataParams) (*TestDefinition, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error)
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (*UpdateUserEmailRow, error)
	UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (*UpdateUserFullNameRow, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (*UpdateUserUsernameRow, error)
	UpdateUserUsernameOrEmail(ctx context.Context, arg UpdateUserUsernameOrEmailParams) (*UpdateUserUsernameOrEmailRow, error)
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
