// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO sessions (
    id,
    user_id,
    session_token_hash,
    ip_address,
    user_agent,
    remember_me,
    expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, session_token_hash, ip_address, user_agent, remember_me, expires_at, revoked, revoked_at, last_activity_at, created_at
`

type CreateUserSessionParams struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	IpAddress        *string            `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	RememberMe       bool               `json:"remember_me"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.SessionTokenHash,
		arg.IpAddress,
		arg.UserAgent,
		arg.RememberMe,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < NOW()
   OR (revoked = TRUE AND revoked_at < NOW() - INTERVAL '7 days')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT
    s.id, s.user_id, s.session_token_hash, s.ip_address, s.user_agent, s.remember_me, s.expires_at, s.revoked, s.revoked_at, s.last_activity_at, s.created_at,
    u.username,
    u.email,
    u.role,
    u.full_name,
    u.title,
    u.is_active,
    u.twofa_enabled
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.session_token_hash = $1
  AND s.revoked = FALSE
  AND s.expires_at > NOW()
`

type GetActiveSessionRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	IpAddress        *string            `json:"ip_address"`
	UserAgent        *string            `json:"user_agent"`
	RememberMe       bool               `json:"remember_me"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	Revoked          bool               `json:"revoked"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastActivityAt   pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Username         string             `json:"username"`
	Email            string             `json:"email"`
	Role             string             `json:"role"`
	FullName         string             `json:"full_name"`
	Title            string             `json:"title"`
	IsActive         bool               `json:"is_active"`
	TwofaEnabled     bool               `json:"twofa_enabled"`
}

func (q *Queries) GetActiveSession(ctx context.Context, sessionTokenHash string) (*GetActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, getActiveSession, sessionTokenHash)
	var i GetActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.IpAddress,
		&i.UserAgent,
		&i.RememberMe,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.TwofaEnabled,
	)
	return &i, err
}

const getActiveSessionsByUser = `-- name: GetActiveSessionsByUser :many
SELECT id, user_id, session_token_hash, ip_address, user_agent, remember_me, expires_at, revoked, revoked_at, last_activity_at, created_at FROM sessions
WHERE user_id = $1
  AND revoked = FALSE
  AND expires_at > NOW()
ORDER BY last_activity_at DESC
`

func (q *Queries) GetActiveSessionsByUser(ctx context.Context, userID uuid.UUID) ([]*Session, error) {
	rows, err := q.db.Query(ctx, getActiveSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SessionTokenHash,
			&i.IpAddress,
			&i.UserAgent,
			&i.RememberMe,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.LastActivityAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE user_id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeAllUserSessionsExcept = `-- name: RevokeAllUserSessionsExcept :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE user_id = $1
  AND id != $2
  AND revoked = FALSE
`

type RevokeAllUserSessionsExceptParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) RevokeAllUserSessionsExcept(ctx context.Context, arg RevokeAllUserSessionsExceptParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessionsExcept, arg.UserID, arg.ID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE id = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByHash = `-- name: RevokeSessionByHash :exec
UPDATE sessions
SET revoked = TRUE, revoked_at = NOW()
WHERE session_token_hash = $1
  AND revoked = FALSE
`

func (q *Queries) RevokeSessionByHash(ctx context.Context, sessionTokenHash string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHash, sessionTokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_activity_at = NOW()
WHERE id = $1
  AND revoked = FALSE
  AND expires_at > NOW()
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
