// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: test_definitions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTestDefinitionAssignments = `-- name: CountTestDefinitionAssignments :one
SELECT COUNT(*) FROM assignments
WHERE test_code = $1
`

// How many assignments reference this instrument. The Developer CRUD
// screen should call this before offering a hard delete — a non-zero
// count means DeleteTestDefinition will fail on the FK, and the UI
// should steer toward SetTestDefinitionActive(false) instead.
func (q *Queries) CountTestDefinitionAssignments(ctx context.Context, testCode string) (int64, error) {
	row := q.db.QueryRow(ctx, countTestDefinitionAssignments, testCode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTestDefinition = `-- name: CreateTestDefinition :one
INSERT INTO test_definitions (
    code, name, domain, scoring_method, requires_sex,
    item_count, typical_duration_minutes,
    source_path, source_checksum
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at,
  (SELECT COUNT(*)::bigint FROM test_definitions) AS total_count
`

type CreateTestDefinitionParams struct {
	Code                   string        `json:"code"`
	Name                   string        `json:"name"`
	Domain                 TestDomain    `json:"domain"`
	ScoringMethod          ScoringMethod `json:"scoring_method"`
	RequiresSex            bool          `json:"requires_sex"`
	ItemCount              int16         `json:"item_count"`
	TypicalDurationMinutes int16         `json:"typical_duration_minutes"`
	SourcePath             string        `json:"source_path"`
	SourceChecksum         string        `json:"source_checksum"`
}

type CreateTestDefinitionRow struct {
	Code                   string             `json:"code"`
	Name                   string             `json:"name"`
	Domain                 TestDomain         `json:"domain"`
	ScoringMethod          ScoringMethod      `json:"scoring_method"`
	RequiresSex            bool               `json:"requires_sex"`
	ItemCount              int16              `json:"item_count"`
	TypicalDurationMinutes int16              `json:"typical_duration_minutes"`
	IsActive               bool               `json:"is_active"`
	SourcePath             string             `json:"source_path"`
	SourceChecksum         string             `json:"source_checksum"`
	Version                int32              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	TotalCount             int64              `json:"total_count"`
}

// Adds a new instrument row after its JSON file has been authored and
// placed at source_path. version starts at 1; is_active defaults to
// TRUE (a newly-added instrument should be immediately assignable
// unless the Developer explicitly deactivates it).
func (q *Queries) CreateTestDefinition(ctx context.Context, arg CreateTestDefinitionParams) (*CreateTestDefinitionRow, error) {
	row := q.db.QueryRow(ctx, createTestDefinition,
		arg.Code,
		arg.Name,
		arg.Domain,
		arg.ScoringMethod,
		arg.RequiresSex,
		arg.ItemCount,
		arg.TypicalDurationMinutes,
		arg.SourcePath,
		arg.SourceChecksum,
	)
	var i CreateTestDefinitionRow
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Domain,
		&i.ScoringMethod,
		&i.RequiresSex,
		&i.ItemCount,
		&i.TypicalDurationMinutes,
		&i.IsActive,
		&i.SourcePath,
		&i.SourceChecksum,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotalCount,
	)
	return &i, err
}

const deleteTestDefinition = `-- name: DeleteTestDefinition :exec
DELETE FROM test_definitions
WHERE code = $1
`

// Hard delete. Will raise a foreign key violation if any assignment
// has ever referenced this code (assignments.test_code is
// ON DELETE RESTRICT, intentionally — deleting an instrument out from
// under historical results would silently corrupt them). Only safe to
// call when CountTestDefinitionAssignments returns 0; otherwise use
// SetTestDefinitionActive to retire it instead.
func (q *Queries) DeleteTestDefinition(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteTestDefinition, code)
	return err
}

const getTestDefinition = `-- name: GetTestDefinition :one

SELECT code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at FROM test_definitions
WHERE code = $1
`

// test_definitions.sql
//
// sqlc queries for the test_definitions table (the instrument catalog).
// Covers two consumers:
//  1. The clinician-facing "Test catalog" view from the mockup (grid
//     of active instruments, click-through to a detail view) and the
//     test picker used when assigning a test to a patient.
//  2. A Developer-role CRUD screen for managing the catalog itself —
//     not shown in the mockup, but requested up front, so the create/
//     update/delete/reactivate shapes below are built for that now
//     rather than bolted on later.
//
// Future-proofing notes:
//   - List queries take LIMIT/OFFSET even though the catalog is small
//     today (4-5 rows) — cheap to include now, and a Developer CRUD
//     screen listing every instrument (active + inactive) is exactly
//     the kind of view that quietly grows over time.
//   - "Metadata" edits (name/domain/scoring_method/requires_sex/
//     item_count/typical_duration_minutes) are a separate query from
//     "source" refreshes (source_path/source_checksum/version). These
//     are two different workflows in the Developer UI — editing catalog
//     facts by hand vs. re-importing a JSON file — and conflating them
//     would make it easy to accidentally bump `version` on a plain
//     metadata edit, or vice versa.
//   - `code` is intentionally never updatable (it's the FK target for
//     assignments.test_code). If a code genuinely needs to change,
//     that's a new row + migrating assignments, not an UPDATE.
//   - DeleteTestDefinition is a real hard delete, left in for
//     completeness, but assignments.test_code has ON DELETE RESTRICT —
//     it will fail with a foreign key violation for any instrument
//     that's ever been assigned. CountTestDefinitionAssignments exists
//     so the Developer UI can check this up front and steer the user
//     toward SetTestDefinitionActive (soft retire) instead of letting
//     them hit a raw DB error.
//
// Full row for one instrument. Used for the catalog detail view and by
// the assignment flow to check is_active/requires_sex/scoring_method
// before letting a clinician assign it.
func (q *Queries) GetTestDefinition(ctx context.Context, code string) (*TestDefinition, error) {
	row := q.db.QueryRow(ctx, getTestDefinition, code)
	var i TestDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Domain,
		&i.ScoringMethod,
		&i.RequiresSex,
		&i.ItemCount,
		&i.TypicalDurationMinutes,
		&i.IsActive,
		&i.SourcePath,
		&i.SourceChecksum,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTestDefinitions = `-- name: ListTestDefinitions :many
SELECT
  td.code, td.name, td.domain, td.scoring_method, td.requires_sex, td.item_count, td.typical_duration_minutes, td.is_active, td.source_path, td.source_checksum, td.version, td.created_at, td.updated_at,
  COUNT(a.test_code)::bigint AS assignment_count
FROM test_definitions td
LEFT JOIN assignments a ON a.test_code = td.code
WHERE
  ($1::bool IS NULL OR td.is_active = $1)
  AND ($2::test_domain IS NULL OR td.domain = $2::test_domain)
GROUP BY td.code          -- adjust to your PK
ORDER BY td.domain, td.name
LIMIT $4 OFFSET $3
`

type ListTestDefinitionsParams struct {
	ActiveOnly *bool       `json:"active_only"`
	Domain     *TestDomain `json:"domain"`
	RowOffset  int32       `json:"row_offset"`
	RowLimit   int32       `json:"row_limit"`
}

type ListTestDefinitionsRow struct {
	Code                   string             `json:"code"`
	Name                   string             `json:"name"`
	Domain                 TestDomain         `json:"domain"`
	ScoringMethod          ScoringMethod      `json:"scoring_method"`
	RequiresSex            bool               `json:"requires_sex"`
	ItemCount              int16              `json:"item_count"`
	TypicalDurationMinutes int16              `json:"typical_duration_minutes"`
	IsActive               bool               `json:"is_active"`
	SourcePath             string             `json:"source_path"`
	SourceChecksum         string             `json:"source_checksum"`
	Version                int32              `json:"version"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	AssignmentCount        int64              `json:"assignment_count"`
}

func (q *Queries) ListTestDefinitions(ctx context.Context, arg ListTestDefinitionsParams) ([]*ListTestDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listTestDefinitions,
		arg.ActiveOnly,
		arg.Domain,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListTestDefinitionsRow
	for rows.Next() {
		var i ListTestDefinitionsRow
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Domain,
			&i.ScoringMethod,
			&i.RequiresSex,
			&i.ItemCount,
			&i.TypicalDurationMinutes,
			&i.IsActive,
			&i.SourcePath,
			&i.SourceChecksum,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AssignmentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshTestDefinitionSource = `-- name: RefreshTestDefinitionSource :one
UPDATE test_definitions
SET
    source_path = $2,
    source_checksum = $3,
    version = version + 1
WHERE code = $1
RETURNING code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at
`

type RefreshTestDefinitionSourceParams struct {
	Code           string `json:"code"`
	SourcePath     string `json:"source_path"`
	SourceChecksum string `json:"source_checksum"`
}

// Called after re-importing an instrument's JSON file (content changed,
// even if the catalog metadata above didn't). Always bumps `version` by
// 1, so a Developer glancing at the row can tell the file was
// re-imported without needing to diff checksums by hand.
func (q *Queries) RefreshTestDefinitionSource(ctx context.Context, arg RefreshTestDefinitionSourceParams) (*TestDefinition, error) {
	row := q.db.QueryRow(ctx, refreshTestDefinitionSource, arg.Code, arg.SourcePath, arg.SourceChecksum)
	var i TestDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Domain,
		&i.ScoringMethod,
		&i.RequiresSex,
		&i.ItemCount,
		&i.TypicalDurationMinutes,
		&i.IsActive,
		&i.SourcePath,
		&i.SourceChecksum,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const searchActiveTestDefinitions = `-- name: SearchActiveTestDefinitions :many
SELECT code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at FROM test_definitions
WHERE is_active
  AND (name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
ORDER BY name
LIMIT $2
`

type SearchActiveTestDefinitionsParams struct {
	Query    *string `json:"query"`
	RowLimit int32   `json:"row_limit"`
}

// Matches the top-nav search bar's placeholder text ("Search patients,
// tests…"), which isn't actually wired to anything in the static
// mockup yet. Trigram/ILIKE match on name or code so it works for
// partial, misspelled, or code-only queries (e.g. typing "bdi").
func (q *Queries) SearchActiveTestDefinitions(ctx context.Context, arg SearchActiveTestDefinitionsParams) ([]*TestDefinition, error) {
	rows, err := q.db.Query(ctx, searchActiveTestDefinitions, arg.Query, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*TestDefinition
	for rows.Next() {
		var i TestDefinition
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Domain,
			&i.ScoringMethod,
			&i.RequiresSex,
			&i.ItemCount,
			&i.TypicalDurationMinutes,
			&i.IsActive,
			&i.SourcePath,
			&i.SourceChecksum,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTestDefinitionActive = `-- name: SetTestDefinitionActive :one
UPDATE test_definitions
SET is_active = $2
WHERE code = $1
RETURNING code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at
`

type SetTestDefinitionActiveParams struct {
	Code     string `json:"code"`
	IsActive bool   `json:"is_active"`
}

// Retire/reactivate toggle — a quick action on the CRUD screen's list
// (e.g. a switch on each row), separate from the full edit form. Retiring
// an instrument doesn't touch its history: existing assignments and
// results referencing this code are untouched, it just stops appearing
// in ListActiveTestDefinitions and can't be picked for new assignments.
func (q *Queries) SetTestDefinitionActive(ctx context.Context, arg SetTestDefinitionActiveParams) (*TestDefinition, error) {
	row := q.db.QueryRow(ctx, setTestDefinitionActive, arg.Code, arg.IsActive)
	var i TestDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Domain,
		&i.ScoringMethod,
		&i.RequiresSex,
		&i.ItemCount,
		&i.TypicalDurationMinutes,
		&i.IsActive,
		&i.SourcePath,
		&i.SourceChecksum,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateTestDefinitionMetadata = `-- name: UpdateTestDefinitionMetadata :one
UPDATE test_definitions
SET
    name = $2,
    domain = $3,
    scoring_method = $4,
    requires_sex = $5,
    item_count = $6,
    typical_duration_minutes = $7
WHERE code = $1
RETURNING code, name, domain, scoring_method, requires_sex, item_count, typical_duration_minutes, is_active, source_path, source_checksum, version, created_at, updated_at
`

type UpdateTestDefinitionMetadataParams struct {
	Code                   string        `json:"code"`
	Name                   string        `json:"name"`
	Domain                 TestDomain    `json:"domain"`
	ScoringMethod          ScoringMethod `json:"scoring_method"`
	RequiresSex            bool          `json:"requires_sex"`
	ItemCount              int16         `json:"item_count"`
	TypicalDurationMinutes int16         `json:"typical_duration_minutes"`
}

// Edits the catalog-facing facts a Developer would change by hand in
// the CRUD screen. Deliberately excludes `code` (immutable) and the
// source_path/source_checksum/version trio (see RefreshTestDefinitionSource) —
// these are two different edit workflows in the UI, not one form.
func (q *Queries) UpdateTestDefinitionMetadata(ctx context.Context, arg UpdateTestDefinitionMetadataParams) (*TestDefinition, error) {
	row := q.db.QueryRow(ctx, updateTestDefinitionMetadata,
		arg.Code,
		arg.Name,
		arg.Domain,
		arg.ScoringMethod,
		arg.RequiresSex,
		arg.ItemCount,
		arg.TypicalDurationMinutes,
	)
	var i TestDefinition
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Domain,
		&i.ScoringMethod,
		&i.RequiresSex,
		&i.ItemCount,
		&i.TypicalDurationMinutes,
		&i.IsActive,
		&i.SourcePath,
		&i.SourceChecksum,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
