// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: twofa_backup_code.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countUnusedBackupCodesForUser = `-- name: CountUnusedBackupCodesForUser :one
SELECT count(*)
FROM twofa_backup_codes
WHERE user_id = $1 AND used = FALSE
`

func (q *Queries) CountUnusedBackupCodesForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedBackupCodesForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBackupCodes = `-- name: CreateBackupCodes :exec
INSERT INTO twofa_backup_codes (
    id, user_id, code_hash
) VALUES (
    unnest($1::uuid[]), unnest($2::uuid[]), unnest($3::text[])
)
`

type CreateBackupCodesParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
	Column3 []string    `json:"column_3"`
}

func (q *Queries) CreateBackupCodes(ctx context.Context, arg CreateBackupCodesParams) error {
	_, err := q.db.Exec(ctx, createBackupCodes, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const deleteUserBackupCodes = `-- name: DeleteUserBackupCodes :exec
DELETE FROM twofa_backup_codes
WHERE user_id = $1
`

func (q *Queries) DeleteUserBackupCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserBackupCodes, userID)
	return err
}

const getBackupCodeByHash = `-- name: GetBackupCodeByHash :one
SELECT id, user_id, used
FROM twofa_backup_codes
WHERE code_hash = $1
`

type GetBackupCodeByHashRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Used   bool      `json:"used"`
}

func (q *Queries) GetBackupCodeByHash(ctx context.Context, codeHash string) (*GetBackupCodeByHashRow, error) {
	row := q.db.QueryRow(ctx, getBackupCodeByHash, codeHash)
	var i GetBackupCodeByHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.Used)
	return &i, err
}

const getUnusedBackupCodesForUser = `-- name: GetUnusedBackupCodesForUser :many
SELECT id, code_hash
FROM twofa_backup_codes
WHERE user_id = $1 AND used = FALSE
`

type GetUnusedBackupCodesForUserRow struct {
	ID       uuid.UUID `json:"id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) GetUnusedBackupCodesForUser(ctx context.Context, userID uuid.UUID) ([]*GetUnusedBackupCodesForUserRow, error) {
	rows, err := q.db.Query(ctx, getUnusedBackupCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetUnusedBackupCodesForUserRow
	for rows.Next() {
		var i GetUnusedBackupCodesForUserRow
		if err := rows.Scan(&i.ID, &i.CodeHash); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBackupCodeUsed = `-- name: MarkBackupCodeUsed :exec
UPDATE twofa_backup_codes
SET used = TRUE
WHERE id = $1
`

func (q *Queries) MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBackupCodeUsed, id)
	return err
}
