// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupInactiveUsers = `-- name: CleanupInactiveUsers :exec
DELETE FROM users
WHERE is_active = FALSE
`

func (q *Queries) CleanupInactiveUsers(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupInactiveUsers)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, role, username, email, full_name, title, password_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, role, username, email, full_name, title, is_active, is_email_verified,
         twofa_enabled, last_login, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Role         string    `json:"role"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	FullName     string    `json:"full_name"`
	Title        string    `json:"title"`
	PasswordHash string    `json:"password_hash"`
}

type CreateUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Role,
		arg.Username,
		arg.Email,
		arg.FullName,
		arg.Title,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableUser2FA = `-- name: DisableUser2FA :exec
UPDATE users
SET twofa_secret = NULL, twofa_enabled = FALSE
WHERE id = $1
`

func (q *Queries) DisableUser2FA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUser2FA, id)
	return err
}

const enableUser2FA = `-- name: EnableUser2FA :exec
UPDATE users
SET twofa_secret = $1, twofa_enabled = TRUE
WHERE id = $2
`

type EnableUser2FAParams struct {
	TwofaSecret *string   `json:"twofa_secret"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) EnableUser2FA(ctx context.Context, arg EnableUser2FAParams) error {
	_, err := q.db.Exec(ctx, enableUser2FA, arg.TwofaSecret, arg.ID)
	return err
}

const existDeveloperAccount = `-- name: ExistDeveloperAccount :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE role = 'DEVELOPER'
)
`

func (q *Queries) ExistDeveloperAccount(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, existDeveloperAccount)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserWithEmail = `-- name: ExistsUserWithEmail :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE email = $1
)
`

func (q *Queries) ExistsUserWithEmail(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserWithEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsUserWithUsername = `-- name: ExistsUserWithUsername :one
SELECT EXISTS(
    SELECT 1
    FROM users
    WHERE username = $1
)
`

func (q *Queries) ExistsUserWithUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, existsUserWithUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getPasswordHash = `-- name: GetPasswordHash :one
SELECT password_hash
FROM users
WHERE id = $1
`

func (q *Queries) GetPasswordHash(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPasswordHash, id)
	var password_hash string
	err := row.Scan(&password_hash)
	return password_hash, err
}

const getUser2FASecret = `-- name: GetUser2FASecret :one
SELECT username, email, full_name, title, role, twofa_secret, password_hash
FROM users
WHERE id = $1 AND twofa_enabled = TRUE
`

type GetUser2FASecretRow struct {
	Username     string  `json:"username"`
	Email        string  `json:"email"`
	FullName     string  `json:"full_name"`
	Title        string  `json:"title"`
	Role         string  `json:"role"`
	TwofaSecret  *string `json:"twofa_secret"`
	PasswordHash string  `json:"password_hash"`
}

func (q *Queries) GetUser2FASecret(ctx context.Context, id uuid.UUID) (*GetUser2FASecretRow, error) {
	row := q.db.QueryRow(ctx, getUser2FASecret, id)
	var i GetUser2FASecretRow
	err := row.Scan(
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.Role,
		&i.TwofaSecret,
		&i.PasswordHash,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, username, email, full_name, title, is_active,
       is_email_verified, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT
    id,
    role,
    username,
    email,
    full_name,
    title,
    password_hash,
    is_active,
    is_email_verified,
    twofa_enabled,
    last_login,
    created_at,
    updated_at
FROM users
WHERE (email = $1 OR username = $1)
  AND is_active = TRUE
`

type GetUserByEmailOrUsernameRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	PasswordHash    string             `json:"password_hash"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (*GetUserByEmailOrUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i GetUserByEmailOrUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, username, email, full_name, title, is_active,
       is_email_verified, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, username, email, full_name, title, is_active,
       is_email_verified, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserCountBySearch = `-- name: GetUserCountBySearch :one
WITH search_input AS (
    SELECT
        $1::text AS raw
)
SELECT COUNT(*)
FROM users, search_input
WHERE
    (
        $1 = ''
        OR username % raw
        OR email % raw
    )
    AND ($2 = '' OR role = $2)
`

type GetUserCountBySearchParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) GetUserCountBySearch(ctx context.Context, arg GetUserCountBySearchParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCountBySearch, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, role, username, email, full_name, title, is_active, is_email_verified, twofa_enabled, last_login, created_at, updated_at
FROM users
ORDER BY username
LIMIT $1
OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetUsersRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]*GetUsersRow, error) {
	rows, err := q.db.Query(ctx, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetUsersRow
	for rows.Next() {
		var i GetUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Title,
			&i.IsActive,
			&i.IsEmailVerified,
			&i.TwofaEnabled,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, role, username, email, full_name, title, is_active, is_email_verified, twofa_enabled, last_login, created_at, updated_at
FROM users
WHERE role = $1
ORDER BY username
LIMIT $2
OFFSET $3
`

type GetUsersByRoleParams struct {
	Role   string `json:"role"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type GetUsersByRoleRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]*GetUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetUsersByRoleRow
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Title,
			&i.IsActive,
			&i.IsEmailVerified,
			&i.TwofaEnabled,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRoleCount = `-- name: GetUsersByRoleCount :one
SELECT COUNT(*)
FROM users
WHERE role = $1
`

func (q *Queries) GetUsersByRoleCount(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, getUsersByRoleCount, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUsersCount = `-- name: GetUsersCount :one
SELECT COUNT(*)
FROM users
`

func (q *Queries) GetUsersCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getUsersCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const reactivateUser = `-- name: ReactivateUser :exec
UPDATE users
SET is_active = TRUE
WHERE id = $1
`

func (q *Queries) ReactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, reactivateUser, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
WITH search_input AS (
    SELECT
        $1::text AS raw
)
SELECT
    id, role, username, email, full_name, title, is_active, is_email_verified,
    twofa_enabled, last_login, created_at, updated_at,
    GREATEST(
        similarity(username, raw),
        similarity(email, raw)
    ) AS rank
FROM users, search_input
WHERE
    (
        $1 = ''
        OR username % raw
        OR email % raw
    )
    AND ($2 = '' OR role = $2)
ORDER BY rank DESC
LIMIT $3
OFFSET ($4 - 1) * $3
`

type SearchUsersParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Column4 interface{} `json:"column_4"`
}

type SearchUsersRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Rank            interface{}        `json:"rank"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]*SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*SearchUsersRow
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Username,
			&i.Email,
			&i.FullName,
			&i.Title,
			&i.IsActive,
			&i.IsEmailVerified,
			&i.TwofaEnabled,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name     = $2,
    username      = $3,
    email         = $4,
    role          = $5,
    title         = $6,
    is_active     = $7,
    password_hash = COALESCE(NULLIF($8, ''), password_hash)
WHERE id = $1
RETURNING id, username, email, role, full_name, title, is_active, is_email_verified, twofa_enabled, created_at, updated_at, last_login
`

type UpdateUserParams struct {
	ID       uuid.UUID   `json:"id"`
	FullName string      `json:"full_name"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
	Role     string      `json:"role"`
	Title    string      `json:"title"`
	IsActive bool        `json:"is_active"`
	Column8  interface{} `json:"column_8"`
}

type UpdateUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	Role            string             `json:"role"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Username,
		arg.Email,
		arg.Role,
		arg.Title,
		arg.IsActive,
		arg.Column8,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Role,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLogin,
	)
	return &i, err
}

const updateUserEmail = `-- name: UpdateUserEmail :one
UPDATE users
SET
    email          = $1
WHERE id = $2
RETURNING id, role, username, email, full_name, title, is_active, is_email_verified,
         twofa_enabled, last_login, created_at, updated_at
`

type UpdateUserEmailParams struct {
	Email string    `json:"email"`
	ID    uuid.UUID `json:"id"`
}

type UpdateUserEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (*UpdateUserEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserEmail, arg.Email, arg.ID)
	var i UpdateUserEmailRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserFullName = `-- name: UpdateUserFullName :one
UPDATE users
SET
    full_name = $1
WHERE id = $2
RETURNING id, role, username, email, full_name, title, is_active, is_email_verified,
         twofa_enabled, last_login, created_at, updated_at
`

type UpdateUserFullNameParams struct {
	FullName string    `json:"full_name"`
	ID       uuid.UUID `json:"id"`
}

type UpdateUserFullNameRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserFullName(ctx context.Context, arg UpdateUserFullNameParams) (*UpdateUserFullNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserFullName, arg.FullName, arg.ID)
	var i UpdateUserFullNameRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserUsername = `-- name: UpdateUserUsername :one
UPDATE users
SET
    username       = $1
WHERE id = $2
RETURNING id, role, username, email, full_name, title, is_active, is_email_verified,
         twofa_enabled, last_login, created_at, updated_at
`

type UpdateUserUsernameParams struct {
	Username string    `json:"username"`
	ID       uuid.UUID `json:"id"`
}

type UpdateUserUsernameRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserUsername(ctx context.Context, arg UpdateUserUsernameParams) (*UpdateUserUsernameRow, error) {
	row := q.db.QueryRow(ctx, updateUserUsername, arg.Username, arg.ID)
	var i UpdateUserUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserUsernameOrEmail = `-- name: UpdateUserUsernameOrEmail :one
UPDATE users
SET
    username       = $1,
    email          = $2,
    is_email_verified = CASE
        WHEN email IS DISTINCT FROM $2 THEN FALSE
        ELSE is_email_verified
    END
WHERE id = $3
RETURNING id, role, username, email, full_name, title, is_active, is_email_verified,
         twofa_enabled, last_login, created_at, updated_at
`

type UpdateUserUsernameOrEmailParams struct {
	Username string    `json:"username"`
	Email    string    `json:"email"`
	ID       uuid.UUID `json:"id"`
}

type UpdateUserUsernameOrEmailRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	FullName        string             `json:"full_name"`
	Title           string             `json:"title"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserUsernameOrEmail(ctx context.Context, arg UpdateUserUsernameOrEmailParams) (*UpdateUserUsernameOrEmailRow, error) {
	row := q.db.QueryRow(ctx, updateUserUsernameOrEmail, arg.Username, arg.Email, arg.ID)
	var i UpdateUserUsernameOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.FullName,
		&i.Title,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET is_email_verified = TRUE
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
